"""relacionamento tamanhos

Revision ID: 25b6f25f5dbf
Revises: ef62f31829b1
Create Date: 2024-05-10 15:22:57.158707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b6f25f5dbf'
down_revision: Union[str, None] = 'ef62f31829b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
