"""Relacionamento Produto

Revision ID: 6ac4ba1aa409
Revises: 6e83f9decaeb
Create Date: 2024-05-10 15:41:52.614464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac4ba1aa409'
down_revision: Union[str, None] = '6e83f9decaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
