"""Add Coluna Preço ProdutoTamanho

Revision ID: 7e0cbf1803ad
Revises: 9002cb95acf8
Create Date: 2024-05-09 15:45:58.232527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0cbf1803ad'
down_revision: Union[str, None] = '9002cb95acf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_tamanho', sa.Column('preco', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto_tamanho', 'preco')
    # ### end Alembic commands ###
