"""Add Coluna Cor

Revision ID: 9002cb95acf8
Revises: b39f083ac996
Create Date: 2024-05-09 15:21:31.854885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9002cb95acf8'
down_revision: Union[str, None] = 'b39f083ac996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('cor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'cor')
    # ### end Alembic commands ###
