"""Del Coluna cor Produto

Revision ID: ef62f31829b1
Revises: 7e0cbf1803ad
Create Date: 2024-05-09 15:48:44.146163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef62f31829b1'
down_revision: Union[str, None] = '7e0cbf1803ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'cor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('cor', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
