"""relacionamento tamanhos

Revision ID: f234c50d0be5
Revises: 25b6f25f5dbf
Create Date: 2024-05-10 15:23:27.049766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f234c50d0be5'
down_revision: Union[str, None] = '25b6f25f5dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
